[package]
name = "fridgyeast"
version = "0.1.0"
authors = ["Matt Johnston <matt@ucc.asn.au>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
argh = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
regex = "1.3"
atomicwrites = "0.3"

futures = "0.3"
signal-hook = "0.3"
async-io = "1.1"
async-std = { version = "1.6", features = ["attributes"] }
async-trait = "0.1"

act-zero = { version = "0.4", features = ["async-std"] }

config = { version = "0.11", features = ["toml"], default-features = false }

sysfs_gpio = "0.5"

log = "0.4"
simplelog = "0.10"

# tide must match version used in tide-rustls, so have strict versions here
# don't want default logging feature
tide = { version = "= 0.16.0", default-features = false, features = ["h1-server", "sessions"] }
tide-rustls = "= 0.3.0"
tide-compress = "= 0.9.0"
tide-acme = "= 0.1.0"
askama_tide = "= 0.13.0"

askama = { version = "0.10", features = ["serde-json", "with-tide"] }


[profile.release]
opt-level = 's'
lto = "thin"
debug = 0

[profile.dev]
debug = 0

