[package]
name = "fridgyeast"
version = "0.1.0"
authors = ["Matt Johnston <matt@ucc.asn.au>"]
edition = "2018"

[patch.crates-io]
riker = { git = "https://github.com/riker-rs/riker", rev = "2f31854185a5a99cacc3352315d7fae312daec77" }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.7"
slog = { version = "2.5", features = ["release_max_level_debug"] }
slog-scope = "4.3"
slog-term = "2.5"

anyhow = "1.0"
chrono = "0.4"
lazy_static = "1.3"
regex = "1.3"
atomicwrites = "0.2"
# 0.4.1 doesn't work on rpi https://github.com/riker-rs/riker/pull/132
riker = "= 0.4.0"
riker-patterns = "= 0.4.0"
structopt = "0.3"
config = "0.10"
sysfs_gpio = "0.5"
futures = "0.3"

async-std = { version = "1.6", features = ["attributes"] }

# tide must match version used in tide-rustls, so have strict versions here
tide = "= 0.13.0"
tide-rustls = "= 0.1.2"

# askama depends on tide version too
askama_tide = { git = "https://github.com/djc/askama", rev="a94835d6de0add5f9fd6095bbe96525d8ac2579a" }
askama = { git = "https://github.com/djc/askama", rev="a94835d6de0add5f9fd6095bbe96525d8ac2579a", features = ["serde-json", "with-tide"] }
#askama_tide = "0.10"
#askama = { version = "0.10", features = ["serde-json", "with-tide"] }


[profile.release]
opt-level = 's'
lto = true
