[package]
name = "fridgyeast"
version = "0.1.0"
authors = ["Matt Johnston <matt@ucc.asn.au>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
argh = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.7"
regex = "1.3"
atomicwrites = "0.2"

futures = "0.3"
signal-hook = "0.1"
async-io = "1.1"
async-std = { version = "1.6", features = ["attributes"] }
async-trait = "0.1"

#act-zero = { version = "0.3", features = ["async-std"] }
# wait for drop
act-zero= { git = "https://github.com/Diggsey/act-zero", rev = "f2e4ac6f7e451e0c3bad039d601bef7be9de9aeb", features = ["async-std"] }

config = { version = "0.10", features = ["toml"], default-features = false }

sysfs_gpio = "0.5"

log = "0.4"
simplelog = "0.8"

# tide must match version used in tide-rustls, so have strict versions here
# don't want default logging feature
tide = { version = "= 0.14.0", default-features = false, features = ["h1-server", "sessions"] }
tide-rustls = "= 0.1.3"

askama = { version = "0.10", features = ["serde-json", "with-tide"] }
askama_tide = "= 0.11.2"


[profile.release]
opt-level = 's'
lto = "thin"
debug = 0

[profile.dev]
debug = 0

