[package]
name = "fridgyeast"
version = "0.1.0"
authors = ["Matt Johnston <matt@ucc.asn.au>"]
edition = "2018"

[patch.crates-io]
# 0.4 broke running without slog?, but awaiting arm to be fixed
# 0.4.1 doesn't work on rpi https://github.com/riker-rs/riker/pull/132
# https://github.com/riker-rs/riker/issues/131
#riker = { git = "https://github.com/riker-rs/riker", rev = "2f31854185a5a99cacc3352315d7fae312daec77" }
riker = { path = "../riker" }

[dependencies]
anyhow = "1.0"
log-panics = { version = "2.0", features = ["with-backtrace"] }
argh = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.7"
chrono = "0.4"
regex = "1.3"
atomicwrites = "0.2"

futures = "0.3"
signal-hook = "0.1"
async-io = "1.1"
async-std = { version = "1.6", features = ["attributes"] }

config = { version = "0.10", features = ["toml"], default-features = false }

sysfs_gpio = "0.5"

slog = { version = "2.5", features = ["release_max_level_debug"] }
slog-scope = "4.3"
slog-term = "2.6"
slog-stdlog = "4.0"

riker = "= 0.4.1"
riker-patterns = "= 0.4.1"

# tide must match version used in tide-rustls, so have strict versions here
# don't want default logging feature
tide = { version = "= 0.14.0", default-features = false, features = ["h1-server", "sessions"] }
tide-rustls = "= 0.1.3"

askama = { version = "0.10", features = ["serde-json", "with-tide"] }
askama_tide = "= 0.11.2"


[profile.release]
opt-level = 's'
lto = "thin"
debug = 0

[profile.dev]
debug = 0

