[package]
name = "wort-templog"
version = "0.1.0"
authors = ["Matt Johnston <matt@ucc.asn.au>"]
edition = "2018"
default-run = "wort-templog"

#[patch.crates-io]
#riker = { path = "/Users/matt/src/riker" }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.7"
slog = { version = "2.5", features = ["release_max_level_debug"] }
slog-scope = "4.3"
slog-term = "2.5"

chrono = "0.4"
lazy_static = "1.3"
regex = "1.3"
atomicwrites = "0.2"
riker = "0.4"
riker-patterns = "0.4"
structopt = "0.3"
config = "0.10"
anyhow = "1.0"
sysfs_gpio = "0.5"
futures = "0.3"

# tide must match version used in tide-rustls
tide = "0.12"
tide-rustls = "0.1"
async-std = { version = "1.6", features = ["attributes"] }
askama_tide = "0.10"
askama = { version = "0.10", features = ["serde-json", "with-tide"] }


[profile.release]
opt-level = 's'
lto = true
panic = 'abort'
