# An example configuration. This should be saved as fridgyeast.toml
# All options are required.

fridge_delay = 600 # 10 mins to avoid fridge damage from frequent cycling off/on
fridge_wort_invalid_time = 300 # 5 mins
overshoot_interval = 3600 # 1 hour

sensor_base_dir = "/sys/devices/w1_bus_master1"
fridge_gpio_pin = 17
fridge_name = "28-0000042c6dbb"
wort_name = "28-0000042cccc4"

listen = [ ":::4411", ":::4433" ]
ssl_domain = [ "fridge.example.com" ]

# mailto: link for adding session ids uses this address.
# Also used for letsencrypt.
owner_email = "you@example.com"

session_secret = "Put a real secret here, at least 32 characters"

# a list of strings sessionids
allowed_sessions = []
