# An example configuration. This should be saved as local.toml
# All options are required.

fridge_delay = 600 # 10 mins to avoid fridge damage from frequent cycling off/on
fridge_wort_invalid_time = 300 # 5 mins

sensor_base_dir = "/sys/devices/w1_bus_master1"
fridge_gpio_pin = 17
fridge_name = "28-0000042c6dbb"
wort_name = "28-0000042cccc4"

session_secret = "Put a real secret here"

# a list of strings sessionids
allowed_sessions = []
